### ISSUE TITLE
Lots of warnings

### ISSUE THREAD

**Issue by nigelhorne** [mishin/ftree#1]
Hi,

Thanks for your software.  I decided to give it a try, but I get lots of errors running ftree.cgi at the command line with no options:

[Thu Oct 29 12:04:07 2015] ftree.cgi: Argument "__Positional_0001" isn't numeric in postincrement (++) at /Users/hornenj/src/ftree/cgi/lib/Class/Std/Storable.pm line 51.
[Thu Oct 29 12:04:07 2015] ftree.cgi: Argument "__Positional_0001" isn't numeric in postincrement (++) at /Users/hornenj/src/ftree/cgi/lib/Class/Std/Storable.pm line 51.
[Thu Oct 29 12:04:07 2015] ftree.cgi: Argument "__Positional_0001" isn't numeric in postincrement (++) at /Users/hornenj/src/ftree/cgi/lib/Class/Std/Storable.pm line 51.
[Thu Oct 29 12:04:08 2015] ftree.cgi: Strange year: 14282. Year cannot be larger than 2015 at /Users/hornenj/src/ftree/cgi/DataParsers/FieldValidatorParser.pm line 69.
[Thu Oct 29 12:04:08 2015] ftree.cgi: Strange month: 0. Month should be be between 1 and 12 or the name of the month in english at /Users/hornenj/src/ftree/cgi/DataParsers/FieldValidatorParser.pm line 84.
[Thu Oct 29 12:04:08 2015] ftree.cgi: Strange year: 41796. Year cannot be larger than 2015 at /Users/hornenj/src/ftree/cgi/DataParsers/FieldValidatorParser.pm line 69.
[Thu Oct 29 12:04:08 2015] ftree.cgi: Strange year: 12879. Year cannot be larger than 2015 at /Users/hornenj/src/ftree/cgi/DataParsers/FieldValidatorParser.pm line 69.
[Thu Oct 29 12:04:08 2015] ftree.cgi: Strange year: 17372. Year cannot be larger than 2015 at /Users/hornenj/src/ftree/cgi/DataParsers/FieldValidatorParser.pm line 69.
[Thu Oct 29 12:04:08 2015] ftree.cgi: Strange year: 3182. Year cannot be larger than 2015 at /Users/hornenj/src/ftree/cgi/DataParsers/FieldValidatorParser.pm line 69.

**Comment by mishin** [comment]
Hi, nigelhorne!
Well, Now you need start 
https://github.com/mishin/Ftree-cpan
and
https://github.com/mishin/Ftree-cpan/blob/master/cgi-bin/ftree.bat
I put it to cpan, it must run ok
this is old repository

**Comment by nigelhorne** [comment]
Thank you I am trying that.

**Comment by mishin** [comment]
I done it!
